### ISSUE TITLE
Mod doesn't apply to all menus

### ISSUE THREAD

**Issue by ghost** [chloecdn/optionfocusfix#1]
While using this mod, certain menus such as the gamerules menu still have the 1.19.4 bug.

**Comment by LunaticWasTaken** [comment]
Interesting. Gonna look at it, thanks for pointing out!

**Comment by LunaticWasTaken** [comment]
Should now be fixed in the 1.1

Uploaded it on modrinth as well, no idea how long they take to publish, could be instant or some time.

If you still encounter Options that aren't fixed, just reopen the Issue.
