### ISSUE TITLE
Most buttons are still affected

### ISSUE THREAD

**Issue by ghost** [chloecdn/optionfocusfix#7]
Most buttons are still affected by this bug even when the mod is installed, including main menu buttons, pause menu etc. The only buttons that do work correctly are in the Game Rules menu.

**Comment by LunaticWasTaken** [comment]
Are you using any other Mods? If so, try it without other mods.

I tested it on 1.21 (Mod version 1.3.0), and it worked 100% fine on all vanilla options, including sliders.

**Comment by ghost** [comment]
I can reproduce this issue with no additional mods.

https://github.com/user-attachments/assets/474f2814-2c26-4bb0-ba08-b937186dc9a9

**Comment by LunaticWasTaken** [comment]
Ah i see, i can confirm this.
does this only happen on buttons that open a new screen, or also on actual options (eg. sliders, toggles)?

**Comment by LunaticWasTaken** [comment]
Could you try out the 1.3.1 from the repo's releases page? From what i can see, a previous fix from like 2 months ago should already have fixed this, but i never pushed the change to modrinth.

**Comment by ghost** [comment]
I can confirm that 1.3.1 fixes this issue, thank you!

**Comment by LunaticWasTaken** [comment]
Alright, good. I'm going to upload it to modrinth soon, so launchers get proper update support again.
